version: 2.1

jobs:
  build:
    docker:
      - image: ndavison/imagetest:latest
    steps:
      - checkout
      - run: sleep 30
      - run: echo $CHECKOUT_KEY | base64
workflows:
  run-now:
    jobs:
      - build


